language: node_js
node_js:
- '6'
install:
- npm install
- gulp build
script:
- npm test
deploy:
  # skip_cleanup: true
  provider: heroku
  app: cryptic-river-22507
  api_key:
    secure: DJtCtrSmI6GzulOfOaqSAqFXAuBbDQphsM69C8t5HEqPpGmUB2cEdmv2nchx9dghGFscDIQ7D7bDnhmJIWTdrVS9Gy0YIXTVKkCoK/FJqVHTaJx+TnxdnOhUij0vjZXHEOSaNKMrSvVxduqnyGqQvevmlWheZeip7HktiQ6NGjEr14UjZe5jNBwLu5PildurOjgR6RhNerFhDV7w3a5aW9O6WRffmZDOHVsFPdEdEW5ZtdlQ/MCw5ihJ5RyLJqrUoM+dY3fvoCgO7tsn7W0EiIggmp8+SPNn73kMG5i2riHwSOvhxk6xhRDxM+zYbPnJFJRcByljki8mX5uTXHYFblIzfm/N9IYFZJU4zb0rjKQpTesI5KRNdGmAejrkYPeAV4ANmIOwcAFMccFltXXXpoXp56fu1wQ829LVz4epnD+8IWl+DLvMNe+RVV8Xls7hm2wPx0sBX+qF4CcNlg1mSymGz8Cv2gWyMkUB8cloy9y89PgijkQQn7Q+TjZRDn0X619jT++AQxMhmkm4eZ9nCb7lmeQjd4Il7IbZGQl0imotaFa0womi7NukL8qEOVS9PHDM+IvZQEXfVrmTHyDYkXiFkeHAseSnVzWjfFYO9FWZQ93RUhWpGKDw/ZYnZpie6qEfJebVn5EPNWpOTS8nq1F7PWh8uI4bnuAE1HUFL2s=
after_deploy: gulp build